//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncthing4Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncthing4Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] syncthing {
            get {
                object obj = ResourceManager.GetObject("syncthing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Should package assets :/
        ///$(document).ready(function () {
        ///    $(&quot;.navbar-fixed-bottom&quot;).remove();
        ///    $(&quot;.navbar-brand&quot;).remove();
        ///    $(&quot;a[ng-click=&apos;shutdown()&apos;]&quot;).parent().remove();
        ///    $(&quot;#settings .col-md-6&quot;).first().removeClass(&quot;col-md-6&quot;).addClass(&quot;col-md-12&quot;).append($(&quot;#UREnabled&quot;).closest(&quot;.form-group&quot;).detach());
        ///    $(&quot;#settings .col-md-6&quot;).last().remove();
        ///    $(&quot;a[href*=http]&quot;).attr(&quot;href&quot;, &quot;&quot;);
        ///
        ///    $(&quot;&lt;style type=&apos;text/css&apos;&gt;&quot;).html(&quot;.modal-backdrop.in { opacity: 0; }&quot;).appendTo(&quot;hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wrapper {
            get {
                return ResourceManager.GetString("wrapper", resourceCulture);
            }
        }
    }
}
